modis_gldas_lst_aio_monitor:modis_gldas_lst_aio_monitor.cpp
	g++ -ldl -pthread -I/usr/include/mysql/ -I.  -o modis_gldas_lst_aio_monitor  modis_gldas_lst_aio_monitor.cpp /usr/lib64/mysql/libmysqlclient.a -lgdal

